### ISSUE TITLE
Suggestion: combined run method

### ISSUE THREAD

**Issue by Ferk** [NovaSquirrel/NovaTheSquirrel#82]
I've been checking on your project for a while, it looks very promising, congrats!

One thing I've noticed is that while the default run method makes it impossible to shoot while moving, the alternative one (the double tap to run) makes it a bit uncomfortable/unconventional to run, specially when switching directions while running.

Why not do like in Super Mario Bros 3 where the B button will shoot even while moving while at the same time allows running while pressed?

It might cause you to shoot unintentionally sometimes, but I think that would be ok in most cases. You could still keep the double tap for running without shooting for the cases were you really need to be conservative with the attacks (but so far all the abilities I've seen can be spammed without worries, honestly).

**Comment by NovaSquirrel** [comment]
The original rationale behind avoiding unintentional shots was that I originally envisioned the game as having a lot more interaction between player projectiles and the environment. In reality all that really ends up happening is that you can put out campfires (seen in only like a few stages), melt ice, and freeze water/lava.

Aside from level 3-6, none of these things are really that bad to do accidentally, so I've added in an option to let you have this behavior.

**Comment by Ferk** [comment]
That was fast! Thank you.

I understand the original rationale. Though with a combined run method it would have still been possible to be careful when shooting by using double tapping for running when close to ice/water/lava, and yet be still able to use B for running/shooting when not. The "B always shoots" option only makes sense with "B" run method and makes no difference with "tap" run method.

Is there any ability that requires you to hold B or are they all instant shooting? (I have to confess I haven't completed all the levels yet)

If no abilities require holding B, maybe holding B for run doesn't need to be an option, and instead of "Run method: b/tap" do: "double tap to run: yes/no" so double tapping is an addition rather than an alternative that removes the "hold B to run" (before I noticed you changes I had tested this moving [these 3 lines up ](https://github.com/NovaSquirrel/NovaTheSquirrel/blob/master/src/player.s#L1135-L1137) so they happen regardless).

**Comment by NovaSquirrel** [comment]
You want it so you can run Mario-style or Kirby style on the same movement setting? I can do that, though it looks more complicated than just moving those lines up.

All of the abilities just trigger an action when B is tapped and nothing requires you to hold it, so holding B to run won't affect anything ability-wise.

I'll try to figure out how the options can be improved.
