### ISSUE TITLE
Redo run related options

### ISSUE THREAD

**Issue by NovaSquirrel** [NovaSquirrel/NovaTheSquirrel#86]
While the rest of the options worked fine with only 2 choices, each 4 characters long, I think running will need more flexibility and I think it would make sense to have the following four choices:

- Press B to attack when standing or in the air, hold B while walking to run (current default)
- Press B at any time to attack, hold B to run
- Press B at any time to attack, double-tap d-pad to run
- Press B at any time to attack, hold B to run, double tap d-pad to run (new default?)

I'll have to come up with shorter names for these before I can have them as menu choices too.

**Comment by Ferk** [comment]
If there are no attacks that require holding B, why not make holding B run in all cases? without needing an option for it.
Then you could have all possibilities (except the third) with only 2 options and you wouldn't need to come up with names for it:

- Run with double tap: yes/no
- Attack while moving: yes/no

Option 1 (current default) would be "no/no", option 2: "no/yes", and option 4 would be "yes/yes".

This doesn't cover case 3, but in turn it gives a different option: "yes/no" (which is basically the current default behavior + being able to do tap to run as well).

**Comment by NovaSquirrel** [comment]
Really my main concern that would justify case 3 is that without it, you would start to speed up briefly when you tap the attack button while walking and that sounds like it could be annoying. I'm going to implement your idea though, and if it's actually a problem I'll see if something else is needed.

**Comment by NovaSquirrel** [comment]
Implemented, hopefully that should be everything that needs to be done for running.
